### ISSUE TITLE
IW3 - Any possibility of a realtime mode? (iw3.desktop general)

### ISSUE THREAD

**Issue by IkariDevGIT** [nagadomi/nunif#319]
I really think adding a real-time mode could be a solid addition. I don’t know all the technical details on how it would work under the hood, but the benefits are definitely there. Here are a few ways it could be useful:  

- Streaming without having to wait for a full video to download, this could work for a series, movies, anime, YouTube videos, or whatever else someone wants to watch. 
- Flatscreen gaming.  

To give some context on how this would even be used, there’s a program called Virtual Desktop that lets you remote into your PC using VR. It has an SBS mode, which means you can already watch anything on your PC in 3D if the output is SBS. If real-time support were possible, this could make that everything you see on your pc into 3D.  

I actually think it would be pretty practical. I only have 12GB of VRAM and still manage to get around 26 FPS with IW3, and that’s with just a slight adjustment to the default config.  

Not sure how realistic this is, but I’d love to hear your thoughts on it!

**Comment by nagadomi** [comment]
If you specify `Video Format=mkv`, you can playback the output mkv video during conversion.
And SKYBOX and Pigasus support SMB (Windows Shared Folder).
By playback mkv via SMB, the video during conversion can be playback in near realtime.

However, those who want realtime actually expect to be able to choose the video they want to play from the VR headset.
So I think that the request regarding **realtime** is about UI and what is needed is the development of a video player or DLNA server.

**Comment by IkariDevGIT** [comment]
@nagadomi Thank you for the response!

What I’m suggesting isn’t about watching a file while it’s being converted. It’s rather about applying the depth estimation and 3D conversion in real-time to anything displayed on a PC screen, including games, web videos, or live streams. Essentially, the idea would be to process frames dynamically as they appear, rather than converting a pre-existing video file.

The reason I brought up Virtual Desktop is that it already allows you to stream your PC screen to VR with SBS support. If IW3 had a real-time mode, it could theoretically take the live video feed from a PC screen and apply its depth-based conversion before sending it to VR, effectively turning anything you see into 3D.

**Comment by nagadomi** [comment]
Maybe it is technically possible.
- ffmpeg can take screen recordings as input and output realtime stream such as RTMP.
- Since iw3 uses ffmpeg bindings, it can input the desktop stream, convert it to 3D, and output another stream.
- Several VR video players can play streaming video.

However, the results other than full screen playback maybe not good.

**Comment by nagadomi** [comment]
If it's a toy level (HTML5 Video player with MJPEG stream, maybe laggy),
I can develop it in a day, I'll give it a try.

**Comment by nagadomi** [comment]
I implemented this.
It works better than I expected, but when I look at GUI windows other than full screen video, it is slightly distorted and makes me 3D sickness.

**Comment by nagadomi** [comment]
If anyone gets interested, please give it a try.

switch to the dev branch first.
https://github.com/nagadomi/nunif/blob/dev/windows_package/docs/README.md#dev-branch

then see
https://github.com/nagadomi/nunif/blob/dev/iw3/docs/desktop.md

**Comment by IkariDevGIT** [comment]
I tested it, and I’m genuinely impressed that you were able to implement this in just one day, it works pretty good!

I had a couple of questions and suggestions regarding performance optimizations:  

1. **Batch Size for Real-Time Mode** – Is batch size adjustable in real-time mode? Allowing it to process multiple frames at once could help improve performance on lower-end GPUs, even if it introduces some latency.  

2. **Frame Interpolation for Depth Processing** – A potential optimization could be an option to process depth estimation only every *n* frames (e.g., every 2 frames) and interpolate the depth information between them. This would likely introduce some latency but could significantly improve FPS while maintaining reasonable depth accuracy.  

Let me know what you think! I’d be happy to test any further improvements.

**Comment by IkariDevGIT** [comment]
Little follow-up to my last message:

I wanted to propose an additional optimization that could help improve performance in real-time mode. Instead of processing depth estimation for every frame, an adaptive motion-based depth frame skipping mechanism could be implemented.

The idea is to dynamically adjust depth processing frequency based on motion intensity:

- High Motion: If significant movement is detected between consecutive frames, depth estimation would be computed normally for each frame.
- Low/No Motion: If little to no movement is detected, instead of recalculating depth, the previous depth frame would be reused or interpolated between the depth frames for rendering, reducing the computational load.

Combining motion-based depth frame skipping + depth frame skipping with with interpolation + proper batch size implementation for real-time mode (may already exist, but my testing didn’t yield noticeable improvements) could lead to significantly better performance and higher FPS.

**Comment by nagadomi** [comment]
I will consider improving the FPS, but when using Any_V2_S,  it seems that the performance of depth estimation model is not a bottleneck.

On my machine(RTX3070Ti), the performance of Any_V2_S itself can achieve about 120 FPS even with batch-size=1.
But with `python -m iw3.desktop --depth-model Any_V2_S` it only achieves about 14 FPS.

Increasing the batch size will be helpful for improvement because it can improve everything including device memory transfer, image resizing and warping, etc.

**Comment by IkariDevGIT** [comment]
Wait, what? I'm barely getting 17 FPS in normal mode and around 7–9 FPS in desktop mode.  

My specs:  
CPU: Intel Core i9-10850K  
RAM: 16GB (3200MHz)  
Storage: Installed on an SSD  
GPU: RTX 3060  

Any idea what could be causing this?

**Comment by nagadomi** [comment]
I made some minor improvements to iw3.desktop. 14FPS->24FPS. JPEG encoding was slow, I changed that.

---
120 FPS is the performance of the depth estimation model itself, not the video conversion.
https://github.com/nagadomi/nunif/blob/b3a5208c979528bb0417712a06f667a9b25465c1/iw3/depth_anything_model.py#L235-L252
I changed `B = 4` -> `B = 1`, `Any_L` -> `Any_V2_S`,
then
```
python -m iw3.depth_anything_model
```

---

Video conversion speed depends on the resolution of the input video, but can achieve 30 FPS(*1) for HD and 100 FPS for SD on my machine.
*1: 30FPS is same result as Any_B, most of the processing time is other than depth estimation

If you think your env is too slow, check the following.
- Depth Model: Any_V2_S
- Depth Batch Size: 4
- Worker Threads: 4
- FP16: ON
- Stream: ON
- TTA: OFF
- Low VRAM: OFF

other settings are default values

**Comment by IkariDevGIT** [comment]
After implementing these changes, my performance has improved to around 15-17 FPS on average, already a good improvement. Do you have any additional ideas for further optimizing performance?  

Also, I believe the following features would greatly enhance usability, particularly when the user is not directly in front of the PC:  

- Simple controls: Basic input methods such as mouse clicks, scrolling and keyboard inputs would make it much more easier to use.  
- Audio transmission: The ability to transmit audio would be a valuable addition.

**Comment by Salmaun321** [comment]
Hi, first of all, nice work!

I can get over 800fps in the benchmark if I set batch size = 8, but only about 27fps streaming, my specs:
CPU: Intel Core i5-13600K
RAM: 32GB 
GPU: RTX 4090

it seems that changing the preset, model or CRF etc, makes little to no effect

**Comment by nagadomi** [comment]
I parallelized screenshot and 3D conversion. on my machine improved 24FPS -> 48FPS.
And probably due to browser limitations, video updates will not perform above 30 FPS, so this should be sufficient performance.

@Salmaun321 
>it seems that changing the preset, model or CRF etc, makes little to no effect

iw3.desktop uses JPEG sequential images(MJPEG) and not video codecs, so those options are ignored.
You can only specify `--stream-quality` options for MJPEG. `--stream-quality 90` by default. When lower quality value is specified, network traffic can be reduced.

**Comment by Salmaun321** [comment]
That last update really helped I'm getting ~60fps. I'm using the Pico 4 default browser,  now the issue is that it doesn't get the right aspect ratio, I always get a square image no matter if I set half or full sbs.

**Comment by loawizard** [comment]
Would this work for projector too. If I use mibox

**Comment by loawizard** [comment]
can you change depthsetting too?

**Comment by loawizard** [comment]
this is dream come true for me! i only have 17 frames though on 4070ti. watching on my browser app in mibox

**Comment by nagadomi** [comment]
@Salmaun321 
I added `--full-sbs` option. Half SBS by default, because Meta Quest's browser only supports Half SBS.
`python -m iw3.desktop --stream-fps 30 --full-sbs`

@loawizard 
You can set target Streaming FPS with `--stream-fps` option. 15FPS by default.
Also, as far as I have tried, it does not work correctly above 30. Probably due to some limitation of browser.
I may change the default to `--stream-fps 30` eventually.

---
Also note that while iw3.desktop web page is open on the PC side, performance will be degraded due to browser rendering load.

**Comment by Salmaun321** [comment]
With the full-sbs option the aspect ratio was solved, but I noticed another issue.

If I start the stream it reaches 60+fps, then over time stabilizes to ~40 while on the desktop, but as soon as I open any fullscreen video it gradually drop to ~12fps

**Comment by francdn** [comment]
Does anyone know how to watch on the apple vision pro? Safari browser does not seem to play the sbs in 3d.

**Comment by nagadomi** [comment]
@Salmaun321 
I fixed it probably. Update and try again.

**Comment by nagadomi** [comment]
@francdn 
I only have Meta Quest so I don't know anything about the other devices.

Is the video not animated and only the first frame is displayed? Or no image is shown at all?
Safari's HTML5 video player does not support 3D display?

**Comment by francdn** [comment]
The video plays but not in 3d. I can only see the sbs image.

**Comment by nagadomi** [comment]
This can be used with any VR video player that allows playback by specifying a video URL(and MJPEG video), but I don't know which players support this.
The URI of the streaming video is `/stream.jpg`. e.g, `http://192.168.11.2:1303/stream.jpg`
 (Maybe I need to change it to something like `sream_LR.avi`, but I haven't figured anything yet.)

**Comment by Salmaun321** [comment]
Dude, you're awesome, now its playing at 28fps very stable.

Still lacks audio, but man, that's incredible, anything real time 2d to 3d better than any pre rendered movie, fucking awesome

**Comment by nagadomi** [comment]
You can use your PC's headphones to play audio, not the VR headset's headphones.

**Comment by loawizard** [comment]
got Estimated FPS = 19.85, Streaming FPS ! much better already!

python -m iw3.desktop --depth-model Any_V2_S --divergence 2.75 --convergence 0.7 --batch-size 2 --stream-fps 30

anyway i can crank it up a bit more or have we reached the limit?

**Comment by nagadomi** [comment]
Even if you close the web browser, does it still only run at 20 FPS?
My RTX 3070Ti is probably low performance than RTX 4070, but I'm getting Estimated FPS = 40-50 FPS.
It’s possible that the high screen resolution is the reason. My desktop is HD (1920x1080).

**Comment by nagadomi** [comment]
@loawizard 
I improved screenshot performance. Update and try again.

**Comment by IkariDevGIT** [comment]
@nagadomi Can you please add audio streaming?

**Comment by nagadomi** [comment]
@IkariDevGIT 
You can use your PC's headphones to play audio.

**Comment by IkariDevGIT** [comment]
@nagadomi No, i can't if im not infront of my pc.

**Comment by nagadomi** [comment]
@IkariDevGIT 
If not too far away from the PC, bluetooth wireless earphones should work.
I've never used it but bluetooth 5.1 seems to reach quite a long distance.

**Comment by IkariDevGIT** [comment]
I am far away in another room, also my pc does not support bluetooth and i think many would appriciate this as a feature.

**Comment by nagadomi** [comment]
@IkariDevGIT 
You should be able to use USB Bluetooth adapter.

To add audio support, I would need to rewrite most of the program, so I won’t be implementing it in the near future.
If I ever rewrite it using WebRTC, I might implement it simultaneously.

**Comment by loawizard** [comment]
Estimated FPS = 28.07, Streaming FPS = 21.18192.168.0.252 - - [09/Mar/2025 14:58:33] 

is what i'm getting when i'm not streaming a video yet. so drops to about 19 . which is okay for about 10 minutes than it becomes less comfortable. 

the audio i stream to my bluetooth speaker but there is a second of delay.

my native monitor is 4k but i turned the resolution down to 1920x1080

**Comment by nagadomi** [comment]
@loawizard 
If only Streaming FPS is losw, perhaps JPEG encoder is the bottleneck.
Currently it run on CPU.
It can be run on GPU, but there is a bug in torchvision so it cannot be used until after the release of torch 2.7.

I also changed StreamServer to stop busy waiting and reduce CPU load.
I have not been able to test the effect of this change because Stream FPS is already saturated in my env.

**Comment by loawizard** [comment]
last update lowerd my fps: 

Estimated FPS = 29.51, Streaming FPS = 0.00192.168.0.162 - - [09/Mar/2025 17:23:18] "GET / HTTP/1.1" 200 2873
Estimated FPS = 27.54, Streaming FPS = 18.95192.168.0.162 - - [09/Mar/2025 17:23:22] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 23.75, Streaming FPS = 17.23192.168.0.162 - - [09/Mar/2025 17:23:26] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 22.69, Streaming FPS = 15.86192.168.0.162 - - [09/Mar/2025 17:23:30] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 21.82, Streaming FPS = 15.39192.168.0.162 - - [09/Mar/2025 17:23:34] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 25.51, Streaming FPS = 15.08

**Comment by loawizard** [comment]
I get this on , previous file update.  i still had the zip file 


Estimated FPS = 30.10, Streaming FPS = 0.00192.168.0.252 - - [09/Mar/2025 17:36:33] "GET / HTTP/1.1" 200 2873
Estimated FPS = 29.98, Streaming FPS = 0.00192.168.0.252 - - [09/Mar/2025 17:36:33] "GET /favicon.ico HTTP/1.1" 404 13
Estimated FPS = 29.58, Streaming FPS = 20.82192.168.0.252 - - [09/Mar/2025 17:36:37] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 28.92, Streaming FPS = 20.92192.168.0.252 - - [09/Mar/2025 17:36:41] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 29.07, Streaming FPS = 20.58192.168.0.252 - - [09/Mar/2025 17:36:45] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 28.26, Streaming FPS = 22.11192.168.0.252 - - [09/Mar/2025 17:36:49] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 26.90, Streaming FPS = 20.77192.168.0.252 - - [09/Mar/2025 17:36:53] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 20.15, Streaming FPS = 18.85192.168.0.252 - - [09/Mar/2025 17:36:57] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 19.37, Streaming FPS = 19.35192.168.0.252 - - [09/Mar/2025 17:37:01] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 20.01, Streaming FPS = 19.83192.168.0.252 - - [09/Mar/2025 17:37:05] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 19.69, Streaming FPS = 19.19192.168.0.252 - - [09/Mar/2025 17:37:09] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 21.39, Streaming FPS = 19.71192.168.0.252 - - [09/Mar/2025 17:37:13] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 27.91, Streaming FPS = 21.13192.168.0.252 - - [09/Mar/2025 17:37:17] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 26.67, Streaming FPS = 20.64192.168.0.252 - - [09/Mar/2025 17:37:21] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 26.86, Streaming FPS = 20.88192.168.0.252 - - [09/Mar/2025 17:37:25] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 27.60, Streaming FPS = 20.90192.168.0.252 - - [09/Mar/2025 17:37:29] "GET /process_token HTTP/1.1" 200 29

**Comment by loawizard** [comment]
if i lower the depthmap resolution would that help? is there a command for that?

**Comment by nagadomi** [comment]
I reverted the changes.

You can specify the depth resolution with `--resolution` option
```
python -m iw3.desktop --resolution 252
```

**Comment by loawizard** [comment]
when i increased streaming fps to 60fps i started with higher fps but it goes back to lower then the moment i watch youtube.

192.168.0.252 - - [09/Mar/2025 18:33:39] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 27.52, Streaming FPS = 26.55192.168.0.252 - - [09/Mar/2025 18:33:43] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 23.55, Streaming FPS = 23.32192.168.0.252 - - [09/Mar/2025 18:33:47] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 25.60, Streaming FPS = 24.89192.168.0.252 - - [09/Mar/2025 18:33:51] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 22.90, Streaming FPS = 22.49192.168.0.252 - - [09/Mar/2025 18:33:55] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 19.58, Streaming FPS = 19.39192.168.0.252 - - [09/Mar/2025 18:33:59] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 20.68, Streaming FPS = 19.94192.168.0.252 - - [09/Mar/2025 18:34:03] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 25.97, Streaming FPS = 23.15192.168.0.252 - - [09/Mar/2025 18:34:07] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 26.05, Streaming FPS = 21.12192.168.0.252 - - [09/Mar/2025 18:34:11] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 26.07, Streaming FPS = 20.92192.168.0.252 - - [09/Mar/2025 18:34:15] "GET /process_token HTTP/1.1" 200 2

maybe my pc is'nt fast enough?
13th Gen Intel(R) Core(TM) i5-13600KF   3.50 GHz
32 ram
RTX4070ti

**Comment by loawizard** [comment]
earlier you mentioned these:

Depth Model: Any_V2_S
Depth Batch Size: 4
Worker Threads: 4
FP16: ON
Stream: ON
TTA: OFF
Low VRAM: OFF
other settings are default values

Do you have to use commands to put FP16 , workerthreads and depthbath size and stream on? if so what are they.

**Comment by nagadomi** [comment]
>maybe my pc is'nt fast enough?

I think your PC specs are better than mine, but I use Linux, so it is difficult to tell.
12th Gen Intel(R) Core(TM) i5-12600K, RTX3070ti, 32G RAM.

**Comment by nagadomi** [comment]
I changed to show Screenshot FPS (estimated).
```
Estimated FPS = 45.32, Screenshot FPS = 122.60, Streaming FPS = 29.89
```

**Comment by IkariDevGIT** [comment]
screenshot fps seems to be very low for me @nagadomi
Estimated FPS = 22.06, Screenshot FPS = 34.88

**Comment by loawizard** [comment]
this is what i'm getting now with last file.  the moment it goes from 27 to 20 frames is once i launch youtube video in chrome. maybe i need an alternative to watching stuff in chrome hmnn. still alread

i think i found the problem. when the terminal is not in the foreground and selected, i lose 7 fps. which happens when i go fullscreen

**Comment by nagadomi** [comment]
After I tested on Windows, taking screenshots seemed to be very slow.
So, I’m thinking of implementing a faster screenshot function specialized for Windows.

**Comment by IkariDevGIT** [comment]
@nagadomi oh yes please, that would be awesome.

**Comment by Salmaun321** [comment]
I've no idea how it could work, but it would be nice to use mpc-hc madVR to output directly to 3d stream

**Comment by tufeixp** [comment]
It works quite nice. Hope you are able to bring it to a floating window(bypassing clicks) and capture by window instead of capturing by screen.

**Comment by loawizard** [comment]
Please do make any improvements you can! this real time version is litteraly my dream when it comes to converting as any depth v2 small already creates amazing results

**Comment by IkariDevGIT** [comment]
@nagadomi 

First off, huge thanks for all the work you've put into this project and my idea of this realtime mode. It's seriously impressive, and I really appreciate the time and effort you’ve dedicated to maintaining it.

I've been trying to get audio streaming via WebRTC working, but after multiple attempts, I have to admit it's a bit beyond my skill level. I know you've mentioned before that WebRTC isn’t on the roadmap, but I wanted to ask if you'd reconsider.

Bluetooth isn't a great option for me due to latency issues, and I think WebRTC could be a solid long-term foundation for real-time streaming instead of stacking more optimizations on top of MJPEG. It seems like a natural evolution for the project, and I really believe that with features like this, it could go semi-mainstream for VR users. Improving comfort and usability in VR is a huge deal, and WebRTC could be a huge step in making that happen.

I also think many people would enjoy the better usability this would bring, and I believe a lot of users would agree that this is a great step forward.

I totally get that this is a big ask, so no worries if it’s not something you’re interested in. But if there's anything I can do to help, testing, documentation, anything, I’d be more than happy to contribute.

**Comment by nagadomi** [comment]
I have added `--screenshot` option and two screenshot backends.

`pil` is default screenshot backend. Cross-platform. On Windows, it is slow because it uses classical GDI API. 
```
python -m iw3.desktop --screenshot pil
```

`pil_mp` is a multi-process version of `pil`. It runs on multiple cores, so it should be faster than pil, but it has a higher CPU load.
```
python -m iw3.desktop --screenshot pil_mp
```

`wc_mp` uses Desktop Duplication API provided by [windows_capture](https://github.com/NiiightmareXD/windows-capture) package.
```
python -m iw3.desktop --screenshot wc_mp
```
Desktop Duplication API is a newer API for remote desktop usage that is supposed to be more efficient than classical GDI API. It only works on Windows 10 or later.

**Comment by nagadomi** [comment]
@IkariDevGIT 
It may eventually be supported, but since there are still many missing features, I will add features assuming that users will be in front of their PCs for the time being.

**Comment by loawizard** [comment]
bluetooth latency i resolve with creating a manual delay to bluetooth with bananameter

**Comment by nagadomi** [comment]
I currently plan to add the following features.
- GUI launcher
- Change settings dynamically(realtime) on GUI (mainly for divergence setting)
- (Merge into master branch)

Support for other features will come afterward.
Also this is a personal matter, but I will be away again in April. So if the feature can't be implemented in March, It will be addressed after May.

**Comment by loawizard** [comment]
WOW massive improvements with windows caputere: although sometimes it creates some dips: 

ess_token HTTP/1.1" 200 29
Estimated FPS = 70.09, Screenshot FPS = 134.89, Streaming FPS = 32.37192.168.0.252 - - [12/Mar/2025 09:43:33] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 68.87, Screenshot FPS = 123.21, Streaming FPS = 32.30192.168.0.252 - - [12/Mar/2025 09:43:37] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 45.53, Screenshot FPS = 68.68, Streaming FPS = 32.31192.168.0.252 - - [12/Mar/2025 09:43:41] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 37.11, Screenshot FPS = 88.05, Streaming FPS = 36.68192.168.0.252 - - [12/Mar/2025 09:43:45] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 35.86, Screenshot FPS = 79.37, Streaming FPS = 35.46192.168.0.252 - - [12/Mar/2025 09:43:49] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 34.66, Screenshot FPS = 73.58, Streaming FPS = 34.56192.168.0.252 - - [12/Mar/2025 09:43:53] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 30.61, Screenshot FPS = 42.84, Streaming FPS = 30.25192.168.0.252 - - [12/Mar/2025 09:43:57] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 36.70, Screenshot FPS = 86.35, Streaming FPS = 36.57192.168.0.252 - - [12/Mar/2025 09:44:01] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 22.08, Screenshot FPS = 32.36, Streaming FPS = 21.95192.168.0.252 - - [12/Mar/2025 09:44:05] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 16.67, Screenshot FPS = 21.21, Streaming FPS = 16.84192.168.0.252 - - [12/Mar/2025 09:44:09] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 18.61, Screenshot FPS = 24.49, Streaming FPS = 18.49192.168.0.252 - - [12/Mar/2025 09:44:13] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 22.69, Screenshot FPS = 31.80, Streaming FPS = 21.22192.168.0.252 - - [12/Mar/2025 09:44:17] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 22.35, Screenshot FPS = 30.81, Streaming FPS = 22.15192.168.0.252 - - [12/Mar/2025 09:44:21] "GET /process_token HTTP/1.1" 200 29



I do notice that sometime the video still slightly stuttors at times. Maybe it's the browser app on my android tv box ?( i always watch 30fps in movieplayer without problems.)

**Comment by loawizard** [comment]
i'm confused! the streaming fps is all over the place now:

had it working for 10 minutes above 30fps:
now its goes lower than the previous model at times:

Estimated FPS = 42.37, Screenshot FPS = 54.70, Streaming FPS = 26.16192.168.0.252 - - [12/Mar/2025 09:54:24] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 12.95, Screenshot FPS = 13.65, Streaming FPS = 10.83192.168.0.252 - - [12/Mar/2025 09:54:35] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 10.81, Screenshot FPS = 11.75, Streaming FPS = 9.59192.168.0.252 - - [12/Mar/2025 09:54:39] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 34.05, Screenshot FPS = 42.97, Streaming FPS = 25.90192.168.0.252 - - [12/Mar/2025 09:54:43] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 23.41, Screenshot FPS = 25.63, Streaming FPS = 21.67192.168.0.252 - - [12/Mar/2025 09:54:47] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 21.76, Screenshot FPS = 25.40, Streaming FPS = 17.93192.168.0.252 - - [12/Mar/2025 09:54:51] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 36.86, Screenshot FPS = 47.63, Streaming FPS = 25.97192.168.0.252 - - [12/Mar/2025 09:54:55] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 26.01, Screenshot FPS = 30.34, Streaming FPS = 20.25192.168.0.252 - - [12/Mar/2025 09:54:59] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 48.63, Screenshot FPS = 81.06, Streaming FPS = 30.20192.168.0.252 - - [12/Mar/2025 09:55:03] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 32.11, Screenshot FPS = 37.71, Streaming FPS = 22.69192.168.0.252 - - [12/Mar/2025 09:55:07] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 24.88, Screenshot FPS = 28.32, Streaming FPS = 20.39192.168.0.252 - - [12/Mar/2025 09:55:11] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 23.06, Screenshot FPS = 26.87, Streaming FPS = 18.54192.168.0.252 - - [12/Mar/2025 09:55:15] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 35.71, Screenshot FPS = 43.75, Streaming FPS = 25.51192.168.0.252 - - [12/Mar/2025 09:55:19] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 45.60, Screenshot FPS = 62.86, Streaming FPS = 28.77192.168.0.252 - - [12/Mar/2025 09:55:23] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 26.59, Screenshot FPS = 32.25, Streaming FPS = 19.54192.16



Estimated FPS = 25.85, Screenshot FPS = 44.90, Streaming FPS = 28.55192.168.0.252 - - [12/Mar/2025 09:56:27] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 16.20, Screenshot FPS = 21.18, Streaming FPS = 16.08192.168.0.252 - - [12/Mar/2025 09:56:31] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 11.20, Screenshot FPS = 13.00, Streaming FPS = 11.26192.168.0.252 - - [12/Mar/2025 09:56:35] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 8.30, Screenshot FPS = 9.12, Streaming FPS = 8.43192.168.0.252 - - [12/Mar/2025 09:56:39] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 6.88, Screenshot FPS = 7.29, Streaming FPS = 6.87192.168.0.252 - - [12/Mar/2025 09:56:43] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 6.78, Screenshot FPS = 7.16, Streaming FPS = 6.81192.168.0.252 - - [12/Mar/2025 09:56:47] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 5.83, Screenshot FPS = 6.02, Streaming FPS = 5.93192.168.0.252 - - [12/Mar/2025 09:56:51] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 5.10, Screenshot FPS = 5.16, Streaming FPS = 5.06192.168.0.252 - - [12/Mar/2025 09:56:55] "GET /process_token HTTP/1.1" 200 29
Estimated FPS = 11.10, Screenshot FPS = 13.04, Streaming FPS = 10.87192.168.0.252 - 



this is the command i used: python -m iw3.desktop --depth-model Any_V2_S --divergence 3 --convergence 0.7 --batch-size 2 --stream-fps 60 --screenshot wc_mp

**Comment by loawizard** [comment]
the moment i watch youtube it goes back up to 30's , it's adaptive ?

**Comment by nagadomi** [comment]
Setting higher than `--stream-fps 30`(e.g, 60) will probably cause instability due to browser behavior.
If the instability occurs even with --stream-fps 30, it's probably being affected by the load from other programs, such as video player with hardware acceleration.

It might also be related to the process priority. Not sure if it is effective, but it should be possible to change it from TaskManger. If it is effective, I will be able to set it to a higher priority from the program side.

**Comment by nagadomi** [comment]
I have not yet tested well for problems with long runtimes.
iw3.desktop sometimes performs garbage collection, which may cause it to freeze for one moment.
Also, the browser may have an MJPEG memory leak problem.

**Comment by nagadomi** [comment]
Regarding windows_capture, it may be stopping when there are no screen changes.

**Comment by loawizard** [comment]
OMG its amazing

**Comment by loawizard** [comment]
do still have stutters in video especially when it's moving in video shot but it so much better! thank you so much

**Comment by francdn** [comment]
@nagadomi Would it be too complicated to make run the streaming server in https?

**Comment by nagadomi** [comment]
@francdn 
What is the purpose of that?
SSL setup for local network is very complicated for users. At the least you need to create your own certificates. Additionally, various tricks will be needed to prevent Chrome from reporting SSL errors.

**Comment by francdn** [comment]
> [@francdn](https://github.com/francdn) What is the purpose of that? SSL setup for local network is very complicated for users. At the least you need to create your own certificates. Additionally, various tricks will be needed to prevent Chrome from reporting SSL errors.

Just secure streaming.

**Comment by tufeixp** [comment]
> Regarding windows_capture, it may be stopping when there are no screen changes.

I vote for window capturing support cause I don't have two screens but one glasses-free 3d screen on my desktop.

**Comment by nagadomi** [comment]
@francdn 
iw3.desktop can only bind local network addresses. (unless you specify --bind-addr 0.0.0.0)
That means iw3.desktop is not accessible from the internet.
And the communication between you and the server is not accessible from the internet.
So, it is secure as long as iw3.desktop is used in your home network.

However, it is not recommended to use iw3.desktop on networks that are not managed by you, such as FreeWiFi.
That's the kind of security level iw3.desktop has.

**Comment by nagadomi** [comment]
@tufeixp 
I don't fully understand your environment, but I can support display/monitor selection. I don't plan to support selecting Application Window for now because its size and position can change, and the mouse might get lost.

**Comment by tufeixp** [comment]
> [@tufeixp](https://github.com/tufeixp) I don't fully understand your environment, but I can support display/monitor selection. I don't plan to support selecting Application Window for now because its size and position can change, and the mouse might get lost.

I'm a user of lenovo 27 inches 3d monitor, see : https://www.lenovo.com/nl/nl/p/accessories-and-software/monitors/professional/63f1uar3eu?msockid=2856b3b76490673105dca7fa65f666c5
I have to connect to another 2d screen in order to watch the content converted by iw3.desktop, with the current monitor capturing method. Maybe full screen window selecting and capturing can be easier to support, if size and position really matters?

**Comment by nagadomi** [comment]
@tufeixp 
Selecting the monitor index and region(x, y, width, height) is easy.
Currently, the screen buffer size and streaming video size is fixed at initialization and cannot be changed dynamically.

Your request is to convert application windows on one monitor to 3D and view it on the same monitor?

**Comment by nagadomi** [comment]
@tufeixp 
I don't know how that monitor displays 3D.
Does it support 3D display of SBS images other than browser video?

Anyway, that is different from my intended use, so that support will be later.

**Comment by loawizard** [comment]
If that could be possible it would be could than I can hook up my projector through HDMI.

But how can you capture something in 3d on one screen and display it on same one . That doesn't sound like something that's possibly. If we can capture something on one screen. And display it on another monitor through HDMI . Makes more sense to me

**Comment by francdn** [comment]
Is there anything we have to do so see the cursor in windows? I don't see it with pil.

**Comment by nagadomi** [comment]
@francdn 
With `pil` and `pil_mp`, the mouse cursor is not visible in the screenshot,
so iw3.desktop draws only the position.
pil: 

![Image](https://github.com/user-attachments/assets/a1d54090-f422-4f1a-995f-8eb96997d680)

pil_mp
![Image](https://github.com/user-attachments/assets/0ee19f68-3a58-42c3-87bb-7597372f59d8)

Don't you see these green circles or squares anywhere?
Possibly, the mouse cursor may not be drawn in the correct position due to multiple monitors or DPI settings.
No mouse cursor on both `pil_mp` and `pil`, or only `pil`?

**Comment by francdn** [comment]
I see a small circle but its position does not match the pointer position (and it is not due to lag). I am using 2160p on my computer. See screenshot. The mouse is over "Dark Theme Off" at the right bottom corner and the blue circle shows up more or less in the middle of the screen vertically/horizontally.

<img width="1399" alt="Image" src="https://github.com/user-attachments/assets/8dd772f8-d9e3-4503-8b51-abc737542622" />

If I move close to the left corner of the screen the circle and the pointer align horizontally more or less, but not vertically. See screenshot below. The mouse is over "Inspect" at the left bottom corner and the blue circle shows up more or less in the middle of the screen vertically.

<img width="341" alt="Image" src="https://github.com/user-attachments/assets/0b00e4bf-1e2d-4860-ace5-1577ea894ad0" />

Is it possible that you made the calculations based on a hardcoded resolution?

**Comment by nagadomi** [comment]
@francdn 
It seems to be related to the display scaling setting.
I changed it to 150% and confirmed that the mouse position is incorrect.
I will find out how to fix it.

**Comment by nagadomi** [comment]
@francdn 
Maybe fixed. run update.bat and try again.

**Comment by francdn** [comment]
Thanks a lot. I will try later.

**Comment by loawizard** [comment]
> Setting higher than `--stream-fps 30`(e.g, 60) will probably cause instability due to browser behavior. If the instability occurs even with --stream-fps 30, it's probably being affected by the load from other programs, such as video player with hardware acceleration.
> 
> It might also be related to the process priority. Not sure if it is effective, but it should be possible to change it from TaskManger. If it is effective, I will be able to set it to a higher priority from the program side.

if i dont set it higher then 30 i get 20 fps if i set it to 60 i get steaming fps of 35-36

**Comment by nagadomi** [comment]
@loawizard 
Possibly a problem with the precision of time() and sleep().
I made some changes regarding that. 
And `Sleep Precision` display was added. In my environment it is less than 0.5 ms.
```
Estimated FPS = 42.16, Screenshot FPS = 76.44, Sleep Precision = 0.458 ms, Streaming FPS = 28.08
Estimated FPS = 49.52, Screenshot FPS = 102.61, Sleep Precision = 0.085 ms, Streaming FPS = 29.86
Estimated FPS = 50.36, Screenshot FPS = 101.42, Sleep Precision = 0.090 ms, Streaming FPS = 29.92
Estimated FPS = 52.00, Screenshot FPS = 107.68, Sleep Precision = 0.090 ms, Streaming FPS = 29.94
Estimated FPS = 51.24, Screenshot FPS = 108.07, Sleep Precision = 0.087 ms, Streaming FPS = 29.92
Estimated FPS = 50.16, Screenshot FPS = 102.32, Sleep Precision = 0.461 ms, Streaming FPS = 29.58
Estimated FPS = 50.30, Screenshot FPS = 101.67, Sleep Precision = 0.082 ms, Streaming FPS = 29.96
Estimated FPS = 44.67, Screenshot FPS = 80.84, Sleep Precision = 0.126 ms, Streaming FPS = 29.54
Estimated FPS = 48.08, Screenshot FPS = 99.14, Sleep Precision = 0.086 ms, Streaming FPS = 30.05
Estimated FPS = 43.11, Screenshot FPS = 77.70, Sleep Precision = 0.233 ms, Streaming FPS = 29.29
Estimated FPS = 49.20, Screenshot FPS = 95.15, Sleep Precision = 0.094 ms, Streaming FPS = 29.85
```

**Comment by nagadomi** [comment]
@loawizard 
OK, I confirmed that sleep precision is 15 ms on Python 3.10 + Windows. It was much lower precision than I expected.
So I have fixed it to be around 1 ms. (And `Sleep Precision` display has been removed)
Hopefully the overall FPS instability has been fixed.

**Comment by Salmaun321** [comment]
I noticed another weird behavior, there's seem to be some kind of "motion detection" or "mouse movement detection", that ramps up the screenshot fps when movement is detected, maybe that is what ir causing the stuttering.

[https://youtu.be/ANeygSrZCdU](url)

if there's a way to lock the screenshot fps to the stream fps the playback would be smoother 

I'm using `python -m iw3.desktop --divergence 3 --stream-fps 90 --depth-model Any_V2_S --full-sbs --batch-size 4 --screenshot wc_mp`

**Comment by nagadomi** [comment]
@Salmaun321 
I think that is using windows_capture, but does pil/pil_mp have the same behavior?
Also, Screenshot FPS is estimated value calculated from the time from frame request to response, it is not the running FPS.
pil is running at stream-fps and pil_mp is running at constant 60 fps.

**Comment by nagadomi** [comment]
@Salmaun321 
I changed to allow sending duplicate frames in pil_mp and wc_mp.
Estimated FPS and Stream FPS should no longer be affected by screenshot frequency.

**Comment by loawizard** [comment]
I just tried the gui and the python code i used earlier. fresh reinstall.

for some reason it was extremely choppy and my browser on my android tv kept on crashing so unusable so far i will try the other ones that are not wc_mp

**Comment by loawizard** [comment]
yeah it crashes all my android browsers no matter what settings I choose

**Comment by nagadomi** [comment]
@loawizard 
Did iw3-desktop work in that environment before?
I changed the browser side code which might be the cause. https://github.com/nagadomi/nunif/commit/dd143167afcb684773f35660c87c46a9647f3170
Does it not work only in GUI but work in CLI?

**Comment by nagadomi** [comment]
For now, I changed it to render with requestAnimationFrame again.

**Comment by IkariDevGIT** [comment]
Hey @nagadomi, thanks for merging realtime mode into main and for all the improvements so far. I’m still hitting a critical bottleneck with the current streaming method. The 30 FPS limit, along with browser lag and no audio support, is becoming a real issue for my use cases. I realize I’ve asked a couple of times before, but now it’s impacting practical usability significantly. Is there any possibility of exploring another streaming method, perhaps leveraging a different protocol (like WebRTC) or another approach to optimize performance? I’m more than happy to test out any potential changes or provide further feedback. And again, i am sorry for asking this so much, but this is kind of crucial at this point. Thanks again for your hard work! I definitely noticed the faster overall performance so far tho, so good job on that!

**Comment by nagadomi** [comment]
@IkariDevGIT 
I think I'll wait and see for a while. After all, I've been working on this for the past few weeks...
Also, since many people still haven't used it, various issues may be reported.

Once Torch 2.7 is released, GPU JPEG encoder will be available, so performance will improve even further.
(It already exists, but it's buggy and cannot be used.)

The protocol change might happen at some point later, perhaps in a few months, but it's not certain yet, as I haven't encountered any issues in my environment.
For audio, protocol change is necessary, but regarding performance, it's not yet clear what the bottleneck is.

**Comment by francdn** [comment]
@nagadomi I don't see the option for wc_mp of the desktop gui.

**Comment by nagadomi** [comment]
@francdn 
`wc_mp` option is displayed only if windows_capture package can be imported.
Do you see any errors with the following command?
1. run `nunif-prompt.bat`
2. `python -c "import windows_capture"`

**Comment by loawizard** [comment]
had'nt had time to test the new version yet will test it tonight

**Comment by loawizard** [comment]
seem to be working pretty stable on 29fps

**Comment by nagadomi** [comment]
That's good to hear. I won't be able to access my computer for a few weeks, so I won't be able to make any changes for a while.

**Comment by salexx** [comment]
I've been watching your project for a long time.

This is the most interesting opportunity.

I wanted to implement something like this myself. But, I don't have enough knowledge and time.

On 3090 + Piсo4 it works well already.

Don't abandon this project. It's very interesting!

**Comment by Hussain-X** [comment]
Hi thanks for your continued work on this amazing, game changing, media viewing software. This software is just amazing. Puts me almost inside a movie/tv show with amazing depth instead of the boring 2d, flat viewing.

I hope your month away in April went well. I see you've already updated torch to 2.7. Hopefully the bug to use GPU for JPEG encoding has been fixed.

This is just a bump up to request being able to choose the desktop/monitor to convert to 3D, which was mentioned earlier in this thread, and was also mentioned it can be done easily too. It could solve a lot of problems if implemented.

I experimented using Bigscreen VR to watch a real time conversion of a web video. I used a virtual display driver to add an extra virtual monitor.  Bigscreen VR, the pcvr version, can display only the primary monitor for 3D SBS. At the moment, iw3.desktop appears to also only convert the primary display. Hence there is a clash. If we can choose iw3.desktop to convert the secondary monitor where the web video feed to be converted is also playing, we can then run the output on a web browser (or maybe even VLC) on the same computer's primary display. We can then watch it real time using Bigscreen (and for others, hook it up to a 3D projector). This should also fix the audio issue too since Bigscreen will output the audio too.

Since that isn't working for now (till we can choose a different monitor), I also thought I'd try using a cheap non GPU equipped laptop, install Bigscreen Remote Desktop on it, open the iw3.desktop stream output from the GPU equipped dekstop PC to the laptop browser, then Remote Desktop the laptop to Bigscreen VR standalone on Quest 3. It did work but it was extremely choppy and very low bitrate, without the audio of course. I think my laptop's built in wifi and/or old Intel iGPU, just couldn't handle the traffic.

So being able to choose which monitor to convert should fix all this, then watch the output on the primary display, either via a projector or in my case via Bigscreen PCVR either wired USB or wireless along with the audio. My other reason (along with audio) to want to use Bigscreen VR to view instead of Meta Quest browser is so I can watch live video streams with others too, converted in realtime, e.g. watch live sports in 3D in Bigscreen with others. Hopefully torch 2.7 and usage of GPU to encode JPEG gives me a better stream FPS. I get around stream 20fps at the moment (i5 12500, 4070, 48GB RAM).

**Comment by nagadomi** [comment]
Adding support for monitor index specification is probably possible, but only when using windows_capture (wc_mp) on Windows.

**Comment by nagadomi** [comment]
Now using the GPU JPEG encoder when torch version is >= 2.7. (latest nunif-windows-package)
In my environment, I can already achieve 30FPS, so I don't notice a difference. However, the performance of the JPEG encoder alone has improved from around 80FPS to 160FPS on my setup (1920x1080 RTX 3070ti i5-12600K).

**Comment by francdn** [comment]
With the latest update in windows I get a "grey" frame for every few frames.

**Comment by nagadomi** [comment]
It may still have the bug. I have made GPU JPEG optional.
If the problem occurs only when `GPU JPEG` is turned on, it is probably a bug in the GPU JPEG Encoder.

**Comment by francdn** [comment]
Thanks. I will test soon and let you know.

**Comment by francdn** [comment]
I tested it and it seems to work well with GPU JPEG Encoder disabled.

**Comment by nagadomi** [comment]
Thanks for checking.  On my side as well, when using the large model, I can occasionally see gray frames flicker.

**Comment by francdn** [comment]
I have only tried with the base model but on my end, the frequency on gray frames depends on the output resolution. The higher the output resolution, the more frequent the gray frames.

**Comment by nagadomi** [comment]
I have confirmed that the JPEG Encoded data is corrupted. Perhaps the higher the load, the more frequently it occurs.
I’ve reported it for now, but I’m not sure if it will be addressed. https://github.com/pytorch/vision/issues/8587#issuecomment-2849264295

**Comment by nagadomi** [comment]
I changed it to perform encoding on the main thread when using GPU JPEG.
This seems to have resolved the issue, but performance might be worse.

**Comment by nagadomi** [comment]
From https://github.com/nagadomi/nunif/discussions/381#discussioncomment-13082737 @laiyangli001

I have made some improvements in dev branch, update with update.bat

And try `Screenshot=wc_mp`. It should be the fastest option on Windows. https://github.com/nagadomi/nunif/issues/319
As I mentioned before, higher screen resolutions are slower, so if you’re using 4K, test at 1080p. I added a display of the resized resolution alongside the original screen resolution. If they are the same,no additional resizing is applied.
I tested it on Windows Server 2022 + L4 GPU (Google Cloud remote desktop env), and got  16 Sceenshot FPS with pil_mp and 30 Screenshot FPS with wc_mp.

>Video Encode/Video Decode

It’s probably showing NVENC/NVDEC hardware usage. NVJPEG doesn’t use that hardware, so its load appears under CUDA(3D?). Using hevc_nvenc with iw3 should increase the hardware usage.

**Comment by laiyangli001** [comment]
> I made some minor improvements to iw3.desktop. 14FPS->24FPS. JPEG encoding was slow, I changed that.我对 iw3.desktop 做了一些小改进。14FPS 到 24FPS。JPEG 编码速度很慢，我对此进行了改进。
> 
> 120 FPS is the performance of the depth estimation model itself, not the video conversion.120 FPS 是深度估计模型本身的性能，而不是视频转换的性能。
> 
> [nunif/iw3/depth_anything_model.py](https://github.com/nagadomi/nunif/blob/b3a5208c979528bb0417712a06f667a9b25465c1/iw3/depth_anything_model.py#L235-L252)
> 
> Lines 235 to 252 in [b3a5208](/nagadomi/nunif/commit/b3a5208c979528bb0417712a06f667a9b25465c1)
> 
>  def _bench(): 
>      import time 
>   
>      B = 4 
>      N = 100 
>      model = DepthAnythingModel("Any_L") 
>      model.load(gpu=0) 
>      x = torch.randn((B, 3, 392, 392)).cuda() 
>      model.infer(x) 
>      torch.cuda.synchronize() 
>   
>      with torch.no_grad(): 
>          t = time.time() 
>          for _ in range(N): 
>              model.infer(x) 
>          torch.cuda.synchronize() 
>          print(round(1.0 / ((time.time() - t) / (B * N)), 4), "FPS") 
>   
> 
> I changed `B = 4` -> `B = 1`, `Any_L` -> `Any_V2_S`,
> 我改变了 `B = 4` -> `B = 1` ， `Any_L` -> `Any_V2_S` ，
> then  然后
> ```
> python -m iw3.depth_anything_model
> ```
> 
> Video conversion speed depends on the resolution of the input video, but can achieve 30 FPS(*1) for HD and 100 FPS for SD on my machine.视频转换速度取决于输入视频的分辨率，但在我的计算机上高清可达到 30 FPS(*1)，标清可达到 100 FPS。 *1: 30FPS is same result as Any_B, most of the processing time is other than depth estimation*1：30FPS 与 Any_B 的结果相同，大部分处理时间与深度估计无关
> 
> If you think your env is too slow, check the following.如果您认为您的环境太慢，请检查以下内容。
> 
> * Depth Model: Any_V2_S  深度模型：Any_V2_S
> * Depth Batch Size: 4  深度批次大小：4
> * Worker Threads: 4  工作线程：4
> * FP16: ON  FP16：开启
> * Stream: ON  流：开启
> * TTA: OFF  TTA：关闭
> * Low VRAM: OFF  低 VRAM：关闭
> 
> other settings are default values其他设置均为默认值

@nagadomi Suggest FP16 accuracy option as an open option on the iw3 desktop, where we can freely choose the accuracy. Depending on the computer hardware performance, don't waste it

**Comment by nagadomi** [comment]
@laiyangli001 
It is enabled by default.
The reason I included that option in iw3.gui is to support older GPUs without Tensor Cores.
However, using iw3.desktop on such GPUs is practically impossible due to low performance, so I didn’t add an option to disable it.
In cli, you can disable it with `--disable-amp` option.

enable
```
python -m iw3.desktop --screenshot wc_mp --monitor-index 0
```
disable
```
python -m iw3.desktop --disable-amp --screenshot wc_mp --monitor-index 0
```
In my env, disabling it reduces FPS by half.
